# This is a basic workflow to help you get started with Actions

name: mdBook

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install rust
        run: |
          sudo apt update
          sudo apt install rustc cargo -y
      - name: Install mdBook
        run: cargo install mdbook
      - name: Run mdBook
        run: mdbook build
      - name: Deploy book
        run: |
          git config --global user.email "bczhc0@126.com"
          git config --global user.name "bczhc"
          mv book src/images ..
          git fetch origin
          git switch gh-pages
          rm -rf *
          mv ../book/* .
          mv ../images .
          git add --all
          if [[ `git commit -m update | grep "working tree clean"` != "" ]]; then exit; fi
          git push origin gh-pages -f
